export const SET_MOVIES_PER_PAGE = 'SET_MOVIES_PER_PAGE';

export const LOAD_MOVIES_START = 'LOAD_MOVIES_START';
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const LOAD_MOVIES_ERROR = 'LOAD_MOVIES_ERROR';
